from q1 import *
a=DoublyLinkedList()
assert(a.insert("a", "A"))
assert(a.insert("b", "B"))
assert(a.insert("c", "C"))
a.length()
a.find("c")
assert(a.deleteLast())
assert(a.deleteFirst())
assert(a.deleteLast())
assert(a.deleteFirst())
assert(a.deleteLast())
a.length()
assert(a.insert("a", "A"))
assert(a.insert("b", "B"))
assert(a.insert("c", "C"))
a.length()
assert(a.delete("a"))
assert(a.delete("b"))
a.length()
